_BASE_: video_maskformer2_R50_bs16_8ep.yaml
MODEL:
  CLUSTER_2_FORMER:
    BETA: 1.2
    CLUSTER_WEIGHT: 10.0
    COS_SIM_CLUSTERING_LOSS: true
    DELTA: 1.0
    MAKE_INTER_FRAME_BG_POINTS_CONNECTIONS: true
    MAKE_INTER_FRAME_POINT_CONNECTIONS: true
    MAKE_POSITIVE_BG_PAIRS: false
    MAX_INST: 30
    MAX_NUM_SAMPLE: 20
    MIN_NUM_SAMPLE: 20
    MIN_POINT_PAIR_WEIGHT: 0.9
    TOTAL_INSTANCE_PIXEL_SAMPLE_NUM: 300
    TEST:
      INFERENCE_THRESHOLD: 0.1
  META_ARCHITECTURE: "VideoCluster2Former"
SOLVER:
  BASE_LR: 1.25e-05
  IMS_PER_BATCH: 2
  MAX_ITER: 64000
  STEPS:
  - 44000